name: wf-sockeye
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >= 3.8
  - snakemake >= 5.30
  - mamba
  - drmaa
  - click
  - pandas
  - requests
  - pip
  - pip:
      - python-gitlab

